### ISSUE TITLE
Add sort-imports rules

### ISSUE THREAD

**Issue by bsegault** [emerson-eps/eslint-config#23]
In @epconnect/eventgrid-tools and @epconnect/ui-components, we enforce the [sort-imports](https://eslint.org/docs/rules/sort-imports) rules with some options:
```
"sort-imports": [
      "off",
      {
        "allowSeparatedGroups": true,
        "memberSyntaxSortOrder": ["none", "all", "single", "multiple"],
        "ignoreCase": false
      }
```

It would be nice to have this rule enabled for all projects using the shared eslint config, so that imports follow the same logic in all those projects.

Regarding the options:

- `allowSeparatedGroups`: should be enabled to allow logical groups of imports. Default is `false`
- `memberSyntaxSortOrder`: I personally do not care about this one. Default is `["none", "all", "multiple", "single"],`. Default is fine to me.
- `ignoreCase`: no opinion on that one, default is `false`, I would go for default.

**Comment by bsegault** [comment]
I would also like to suggest an additional practice, but I do not know how to do so.
My idea would be to try to create logical groups:
1. First the native node.js modules
2. Then the imported packages, optionally grouped by prefix 
3. Then the relative imports from the current repository

Maybe it is overkill and not the place to suggest this. I just wanted to expose the idea.

**Comment by alhugot-emr** [comment]
for `ignoreCase` i would go to `true` : Interfaces, classes start with uppercase and function etc, lowercase

**Comment by nicktalb** [comment]
I would also be inclined to set `ignoreCase` to `true`.

> I would also like to suggest an additional practice, but I do not know how to do so.
> My idea would be to try to create logical groups:
> 
> 1. First the native node.js modules
> 2. Then the imported packages, optionally grouped by prefix
> 3. Then the relative imports from the current repository
> 
> Maybe it is overkill and not the place to suggest this. I just wanted to expose the idea.

I'd be happy to have this but if you don't have time to investigate then let's break it out into a separate improvement.

**Comment by nicktalb** [comment]
@bsegault Take a look at [`eslint-plugin-import`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md). Note that this plugin is already included by [`eslint-config-react-app`](https://github.com/facebook/create-react-app/blob/7bdeced8495370b683c08b86bc84b66af83f2f0a/packages/eslint-config-react-app/index.js#L229) but it doesn't look like import order is enabled. We could add it.
